doctrine:

    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'

        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: false
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

            App\Application\EventStore\Domain\EventStore:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Application/EventStore/Infrastructure/Symfony/Doctrine/Mapping'
                prefix: 'App\Application\EventStore\Domain'
                alias: EventStore

            App\Application\UserAccount\Domain\User:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Application/User/Account/Infrastructure/Symfony/Doctrine/Mapping'
                prefix: 'App\Application\User\Account\Domain'
                alias: User

            App\Application\Event\Domain\Event:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Application/Event/Infrastructure/Symfony/Doctrine/Mapping'
                prefix: 'App\Application\Event\Domain'
                alias: Event

            App\Application\Event\Domain\AvailableEventDay:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Application/Event/Infrastructure/Symfony/Doctrine/Mapping'
                prefix: 'App\Application\Event\Domain'
                alias: AvailableEventDay

            App\Application\Event\Domain\ReservedEventDay:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Application/Event/Infrastructure/Symfony/Doctrine/Mapping'
                prefix: 'App\Application\Event\Domain'
                alias: ReservedEventDay

            App\Application\Event\Domain\Reservation:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Application/Event/Infrastructure/Symfony/Doctrine/Mapping'
                prefix: 'App\Application\Event\Domain'
                alias: Reservation

        dql:
            datetime_functions:
                to_date: DoctrineExtensions\Query\Postgresql\StrToDate


when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
